In [24]:
import glob
import pandas as pd
import numpy as npp
import matplotlib.pyplot as plt
import os
import unicodedata
from datetime import datetime
import re

In [25]:
path = "/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/raw"

In [26]:
data_path = glob.glob(f"{path}/*.csv")

data list:
1. Reviews
2. Order items
3. Product category
4. Cutomers
5. Sellers
6. Orders
7. Products
8. Geolocation
9. Payments

In [27]:
data = []
miss = []
for i in data_path:
    buka_data = pd.read_csv(i)
    missing = buka_data.isna().sum()
    data.append(buka_data)
    miss.append(missing)

In [28]:
len(data[8])

103886

In [9]:
data[3]["customer_zip_code_prefix"] = data[3]["customer_zip_code_prefix"].astype('Int64')

In [21]:
# BENAR - row itu 1 baris, bukan seluruh kolom
for _, row in data[3].iterrows():
    zip_code = int(row["customer_zip_code_prefix"]) if pd.notna(row["customer_zip_code_prefix"]) else None

6703

In [ ]:
uuids = [str(uuid4()) for _ in range(len(documents))]

In [29]:
from uuid import uuid4
data[1]["order_item_id"] = [uuid4().hex for _ in range(len(data[1]["order_item_id"]))]

In [30]:
data[1]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,6afecc2e21f548c493fccaecb33438f4,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,bcf71ba6dbf7473e886556fedd5610a6,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,92f8ed3fdc694e76a11c11de5eabbf18,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,07be6d77b056400f9f060fadf7ca656f,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,a2efd8dcbd1740a2b938506f0b21c49c,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,c359c8fbc260410a92f00062ffa10f73,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,59045ee8c1c14176ba2651c8d91fc469,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,53116c105f2a4ca4bb0023754a144e51,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,0cb96a805b9a430d86ad27d80d930bc1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,f189faebcedd4a0fa08050a66a152809,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [5]:
data[1]['total_price'] = data[1]['price'] +  data[1]['freight_value']

In [6]:
def shipping_price_caategory(ongkir):
    if ongkir == 0:
        return "free shipping"
    elif ongkir > 0 and ongkir <= 15:
        return "cheap"
    elif ongkir > 15 and ongkir <=35:
        return "standard"
    elif ongkir > 35 and ongkir <= 70:
        return "expensive"
    else:
        return "very expensive"

data[1]["Shipping category"] = data[1]["freight_value"].apply(shipping_price_caategory)

In [7]:
data[1]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_price,Shipping category
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,cheap
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,standard
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,standard
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,cheap
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,standard
...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,expensive
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,expensive
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,standard
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,cheap
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,cheap

In [23]:
data[6].drop(columns=["product_name_lenght", "product_description_lenght"], inplace=True)
data[6]["product_photos_qty"].fillna(0, inplace=True)

/tmp/ipykernel_1741/1752147659.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[6]["product_photos_qty"].fillna(0, inplace=True)

0        1.0
1        1.0
2        1.0
3        1.0
4        4.0
        ...
32946    2.0
32947    1.0
32948    1.0
32949    2.0
32950    1.0
Name: product_photos_qty, Length: 32951, dtype: float64

In [27]:
data[6].dropna(inplace=True)

In [29]:
len(data[6])

32340

In [12]:
data[6]["product_photos_qty"].fillna(0, inplace=True)

/tmp/ipykernel_1741/3290864389.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data[6]["product_photos_qty"].fillna(0, inplace=True)

0        1.0
1        1.0
2        1.0
3        1.0
4        4.0
        ...
32946    2.0
32947    1.0
32948    1.0
32949    2.0
32950    1.0
Name: product_photos_qty, Length: 32951, dtype: float64

In [9]:
data[6].isna().sum()

product_id                 0
product_category_name    610
product_photos_qty       610
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64

In [ ]:
kolom_cat = ['product_category_name']
kol_num = ["product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"]
for i in kolom_cat:
    data[6][i] = (
        data[6].groupby(
            kol_num,
            dropna=False
        )[i].transform(
            lambda x: x.fillna(x.mode().iloc[0])
            if not x.mode().empty else x
        )
    )

In [ ]:
data[6]["volume"] = data[6]["product_length_cm"] * data[6]["product_height_cm"] * data[6]["product_width_cm"]

In [20]:
def weight_category(berat):
    if berat <= 1000:
        return "light"
    elif berat <= 3000:
        return "medium"
    elif berat <= 10000:
        return "heavy"
    else:
        return "very heavy"
data[6]["weight_category"] = data[6]["product_weight_g"].apply(weight_category)

In [21]:
data[6]

,product_id,product_category_name,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,volume,weight_category
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,1.0,225.0,16.0,10.0,14.0,2240.0,light
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1.0,1000.0,30.0,18.0,20.0,10800.0,light
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,1.0,154.0,18.0,9.0,15.0,2430.0,light
3,cef67bcfe19066a932b7673e239eb23d,bebes,1.0,371.0,26.0,4.0,26.0,2704.0,light
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,4.0,625.0,20.0,17.0,13.0,4420.0,light
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,2.0,12300.0,40.0,40.0,40.0,64000.0,very heavy
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1.0,1700.0,16.0,19.0,16.0,4864.0,medium
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1.0,1400.0,27.0,7.0,27.0,5103.0,medium
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,2.0,700.0,31.0,13.0,20.0,8060.0,light
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,1.0,2083.0,12.0,2.0,7.0,168.0,medium

In [34]:
for i in kol_num:
    data[6][i] = (
        data[6].groupby(
            kolom_cat,
            dropna=False
        )[i].transform(
            lambda x: x.fillna(x.mode().iloc[0])
            if not x.mode().empty else x
        )
    )

In [14]:
data[6].isna().sum()

product_id                 0
product_category_name    392
product_photos_qty       610
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64

In [23]:
for i in kol_num:
    data[6][i] = (
        data[6].groupby(
            kolom_cat
        )[i].transform(
            lambda x: x.fillna(x.mode().iloc[0])
            if not x.mode().empty else x
        )
    )

In [35]:
data[6].isna().sum()

product_id                      0
product_category_name         392
product_name_lenght           392
product_description_lenght    392
product_photos_qty            392
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [12]:
data[8].dtypes
kol_waktu_order = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

In [33]:
product_english_data = pd.read_csv("/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/product_category_name_translation_clean.csv")
product_english = product_english_data.set_index('product_category_name')['product_category_name_english'].to_dict()

In [34]:
product_english

{'beleza_saude': 'health_beauty',
 'informatica_acessorios': 'computers_accessories',
 'automotivo': 'auto',
 'cama_mesa_banho': 'bed_bath_table',
 'moveis_decoracao': 'furniture_decor',
 'esporte_lazer': 'sports_leisure',
 'perfumaria': 'perfumery',
 'utilidades_domesticas': 'housewares',
 'telefonia': 'telephony',
 'relogios_presentes': 'watches_gifts',
 'alimentos_bebidas': 'food_drink',
 'bebes': 'baby',
 'papelaria': 'stationery',
 'tablets_impressao_imagem': 'tablets_printing_image',
 'brinquedos': 'toys',
 'telefonia_fixa': 'fixed_telephony',
 'ferramentas_jardim': 'garden_tools',
 'fashion_bolsas_e_acessorios': 'fashion_bags_accessories',
 'eletroportateis': 'small_appliances',
 'consoles_games': 'consoles_games',
 'audio': 'audio',
 'fashion_calcados': 'fashion_shoes',
 'cool_stuff': 'cool_stuff',
 'malas_acessorios': 'luggage_accessories',
 'climatizacao': 'air_conditioning',
 'construcao_ferramentas_construcao': 'construction_tools_construction',
 'moveis_cozinha_area_de_servico_jantar_e_jardim': 'kitchen_dining_laundry_garden_furniture',
 'construcao_ferramentas_jardim': 'costruction_tools_garden',
 'fashion_roupa_masculina': 'fashion_male_clothing',
 'pet_shop': 'pet_shop',
 'moveis_escritorio': 'office_furniture',
 'market_place': 'market_place',
 'eletronicos': 'electronics',
 'eletrodomesticos': 'home_appliances',
 'artigos_de_festas': 'party_supplies',
 'casa_conforto': 'home_confort',
 'construcao_ferramentas_ferramentas': 'costruction_tools_tools',
 'agro_industria_e_comercio': 'agro_industry_and_commerce',
 'moveis_colchao_e_estofado': 'furniture_mattress_and_upholstery',
 'livros_tecnicos': 'books_technical',
 'casa_construcao': 'home_construction',
 'instrumentos_musicais': 'musical_instruments',
 'moveis_sala': 'furniture_living_room',
 'construcao_ferramentas_iluminacao': 'construction_tools_lights',
 'industria_comercio_e_negocios': 'industry_commerce_and_business',
 'alimentos': 'food',
 'artes': 'art',
 'moveis_quarto': 'furniture_bedroom',
 'livros_interesse_geral': 'books_general_interest',
 'construcao_ferramentas_seguranca': 'construction_tools_safety',
 'fashion_underwear_e_moda_praia': 'fashion_underwear_beach',
 'fashion_esporte': 'fashion_sport',
 'sinalizacao_e_seguranca': 'signaling_and_security',
 'pcs': 'computers',
 'artigos_de_natal': 'christmas_supplies',
 'fashion_roupa_feminina': 'fashio_female_clothing',
 'eletrodomesticos_2': 'home_appliances_2',
 'livros_importados': 'books_imported',
 'bebidas': 'drinks',
 'cine_foto': 'cine_photo',
 'la_cuisine': 'la_cuisine',
 'musica': 'music',
 'casa_conforto_2': 'home_comfort_2',
 'portateis_casa_forno_e_cafe': 'small_appliances_home_oven_and_coffee',
 'cds_dvds_musicais': 'cds_dvds_musicals',
 'dvds_blu_ray': 'dvds_blu_ray',
 'flores': 'flowers',
 'artes_e_artesanato': 'arts_and_craftmanship',
 'fraldas_higiene': 'diapers_and_hygiene',
 'fashion_roupa_infanto_juvenil': 'fashion_childrens_clothes',
 'seguros_e_servicos': 'security_and_services'}

In [10]:
data[5]['order_estimated_delivery_date'] = data[5]['order_estimated_delivery_date'].apply(pd.to_datetime, format='%Y-%m-%d %H:%M:%S')

In [ ]:
kol_waktu_order = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
data[5][kol_waktu_order] = data[5][kol_waktu_order].apply(pd.to_datetime, format='%Y-%m-%d %H:%M:%S')
data[5].to_csv('/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/olist_orders_dataset_clean.csv', index=False)

In [11]:
len(data[6][data[6]['product_weight_g']>10000])

1891

In [62]:
def normalize(data):
    if not isinstance(data, str):
        return data
    kata = unicodedata.normalize('NFKD', data)
    kata_normal = ''.join([i for i in kata if not unicodedata.combining(i)])
    return kata_normal

In [19]:
data[7]['geolocation_city'] = data[7]['geolocation_city'].apply(normalize)

In [47]:
data[0].columns
kol_tanggal = ['review_creation_date', 'review_answer_timestamp']
data[0][kol_tanggal] = data[0][kol_tanggal].apply(pd.to_datetime, format='%Y-%m-%d %H:%M:%S')

In [66]:
data[0].columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [68]:
data_review = ['review_comment_title', 'review_comment_message']
for i in data_review:
    data[0][i] = data[0][i].apply(normalize)
# data[0]['review_comment_message'] = data[0]['review_comment_message'].apply(normalize,na_action='ignore' )

In [69]:
data[0].to_csv('/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/olist_review.csv', index=False)

In [33]:
data[7].to_csv('/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/olist_geolocation_dataset.csv', index=False)

In [20]:
loc_fix = pd.read_csv('/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/olist_geolocation_dataset.csv')

In [21]:
lokasi_zip = loc_fix.drop(columns=['geolocation_lat', 'geolocation_lng', 'geolocation_state']).set_index('geolocation_zip_code_prefix')['geolocation_city'].to_dict()

In [22]:
coba = data[4].copy()

In [14]:
coba

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [23]:
coba['seller_city_fix'] = coba['seller_zip_code_prefix'].map(lokasi_zip)

In [25]:
coba['seller_city'] = coba['seller_city_fix'].combine_first(coba['seller_city'])

In [26]:
coba2 = coba.drop(columns=["seller_city_fix"])

In [27]:
coba2.to_csv('/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/olist_sellers_dataset2.csv', index=False)

In [7]:
penjual = pd.read_csv("/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/olist_sellers_dataset.csv")

In [8]:
penjual

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi-guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [17]:
gabgab = penjual.merge(
    data[4],
    on="seller_id",
    how="left"
)

In [21]:
kos = gabgab[gabgab['seller_city_x'].isna()]
kos

,seller_id,seller_zip_code_prefix_x,seller_city_x,seller_state_x,seller_zip_code_prefix_y,seller_city_y,seller_state_y
473,5962468f885ea01a1b6a97a218797b0a,82040,NaN,PR,82040,curitiba,PR
791,2aafae69bf4c41fbd94053d9413e87ee,91901,NaN,RS,91901,porto alegre,RS
1672,2a50b7ee5aebecc6fd0ff9784a4747d6,72580,NaN,DF,72580,brasilia,DF
1931,2e90cb1677d35cfe24eef47d441b7c87,2285,NaN,SP,2285,sao paulo,SP
2182,0b3f27369a4d8df98f7eb91077e438ac,7412,NaN,SP,7412,aruja,SP
2986,42bde9fef835393bb8a8849cb6b7f245,71551,NaN,DF,71551,brasilia,DF
3028,870d0118f7a9d85960f29ad89d5d989a,37708,NaN,MG,37708,pocos de caldas,MG

In [10]:
gab1 = penjual.merge(
    data[1],
    on="seller_id",
    how="left"
)

In [13]:
gab2 = gab1.merge(
    data[5],
    on="order_id",
    how="left"
)

In [15]:
toko_na = gab2[gab2['seller_city'].isna()]
toko_na

,seller_id,seller_zip_code_prefix,seller_city,seller_state,order_id,order_item_id,product_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
17528,5962468f885ea01a1b6a97a218797b0a,82040,NaN,PR,0a8724bf3ecd49bce712851bbbecaf35,1,48698ba0cfe847b41430fa00081b5619,2017-10-27 00:35:26,39.00,14.10,89aab649693a7e5995fa951d8d2fcdd7,delivered,2017-10-18 23:24:26,2017-10-20 00:35:26,2017-10-24 20:17:49,2017-11-01 19:13:06,2017-11-09 00:00:00
17529,5962468f885ea01a1b6a97a218797b0a,82040,NaN,PR,124fb051a9788c8feb53429fb1612760,1,94aa4a6893284c0236d6c79c194ef5a6,2017-07-07 17:10:15,149.00,16.48,7595f0de4868abaec15c442659fdace2,delivered,2017-07-01 16:58:53,2017-07-01 17:10:15,2017-07-04 06:23:24,2017-07-11 16:42:08,2017-07-28 00:00:00
17530,5962468f885ea01a1b6a97a218797b0a,82040,NaN,PR,21e28426bf49f15032c93153c7a3e206,1,c1b350ede922e02138912a3192bcc86d,2017-10-25 21:56:39,149.00,16.48,ba503b67e4b3b4faef99f1235920617b,delivered,2017-10-18 21:45:26,2017-10-18 21:56:39,2017-10-24 20:17:49,2017-11-03 16:41:38,2017-11-09 00:00:00
17531,5962468f885ea01a1b6a97a218797b0a,82040,NaN,PR,2d58fd72f5132f237b78fe897e578603,1,fb8848eaa1d50492a9c1e8424a86b316,2017-08-11 12:00:22,149.00,14.79,0b85fe0f29638fecccbd53288d8cf0f7,delivered,2017-08-04 11:00:09,2017-08-04 12:00:22,2017-08-07 21:33:40,2017-08-11 22:58:00,2017-08-29 00:00:00
17532,5962468f885ea01a1b6a97a218797b0a,82040,NaN,PR,8d16656866ce7d67f81d49a9707ab76e,1,48698ba0cfe847b41430fa00081b5619,2018-01-03 18:28:04,39.00,15.10,aa1e003c69c80cdf08ae8225270769b3,invoiced,2017-12-25 18:36:16,2017-12-26 18:28:04,NaN,NaN,2018-01-30 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111595,870d0118f7a9d85960f29ad89d5d989a,37708,NaN,MG,eb0786ebf8a32df3392caaf0727e7bbd,1,6fd3f7378cd65325e10cb21733778416,2018-01-03 04:08:44,89.90,13.65,4ea4534f03b9bec97d923dc02b404656,delivered,2017-12-23 21:25:59,2017-12-27 04:08:44,2017-12-28 16:52:23,2018-01-08 22:25:05,2018-01-22 00:00:00
111596,870d0118f7a9d85960f29ad89d5d989a,37708,NaN,MG,fa0eabdc8b8a7fb4e0e95a2b70dabf8b,1,21025aea6e634ed0ab9709a4fa5fb69c,2017-11-16 18:10:34,38.90,14.08,42669d66e9ebba92f46400f726886844,delivered,2017-11-09 17:54:37,2017-11-09 18:10:34,2017-11-13 19:28:35,2017-11-22 00:48:47,2017-11-30 00:00:00
111597,870d0118f7a9d85960f29ad89d5d989a,37708,NaN,MG,fa0eabdc8b8a7fb4e0e95a2b70dabf8b,2,21025aea6e634ed0ab9709a4fa5fb69c,2017-11-16 18:10:34,38.90,14.08,42669d66e9ebba92f46400f726886844,delivered,2017-11-09 17:54:37,2017-11-09 18:10:34,2017-11-13 19:28:35,2017-11-22 00:48:47,2017-11-30 00:00:00
111598,870d0118f7a9d85960f29ad89d5d989a,37708,NaN,MG,faa0a8e07c82b4188dac82ef1d170979,1,f94d494034180bcbeb9c56cae79f6168,2017-12-04 03:47:29,47.90,19.21,9be47708361b959a33fb0b2a537c02ef,delivered,2017-11-25 00:23:59,2017-11-28 04:31:17,2017-11-30 19:28:54,2017-12-15 19:51:54,2017-12-19 00:00:00
111599,870d0118f7a9d85960f29ad89d5d989a,37708,NaN,MG,ffc22f2404e3490516c9a03e88da4507,1,d363e421b1d15376b299089946fed127,2017-11-09 23:46:11,46.99,18.00,127464f7c2d53e47eb1c8b0566b7e78f,delivered,2017-11-05 23:33:03,2017-11-05 23:47:11,2017-11-07 22:23:54,2017-11-16 21:25:51,2017-11-28 00:00:00

In [40]:
data[4]['kota_clean'] = coba['seller_city']
data[4][data[4]['seller_city'] != data[4]['kota_clean']]

,seller_id,seller_zip_code_prefix,seller_city,seller_state,kota_clean
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,mogi-guacu
6,e49c26c3edfa46d227d5121a6b6e4d37,55325,brejao,PE,brejão
19,f9ec7093df3a7b346b7bcf7864069ca3,5138,sao paulo,SP,são paulo
20,4e6015589b781adaa5ce7f1892d06bb1,11440,guaruja,SP,guarujá
28,430315b7bb4b6e4b3c978f9dfa9b0558,4857,sao paulo,SP,são paulo
...,...,...,...,...,...
3026,17e34d8224d27a541263c4c64b11a56b,14085,riberao preto,SP,ribeirao preto
3028,870d0118f7a9d85960f29ad89d5d989a,37708,pocos de caldas,MG,NaN
3044,778323240ce2830d68aab11794e00bfb,13600,sao paulo,SP,araras
3060,21e83881401b92b49fb09a16d3852291,38405,uberlandia,MG,uberlândia
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,taubaté

In [15]:
coba = data[5].groupby("order_status")
coba.get_group("canceled").isna().sum()

order_id                           0
customer_id                        0
order_status                       0
order_purchase_timestamp           0
order_approved_at                141
order_delivered_carrier_date     550
order_delivered_customer_date    619
order_estimated_delivery_date      0
dtype: int64

In [24]:
pd.isna(data[0]['review_comment_message'][0])

True

In [17]:
from qdrant_client import QdrantClient
from langchain_openai import OpenAIEmbeddings
from langchain_core.documents import Document
from langchain_qdrant import QdrantVectorStore
from dotenv import load_dotenv

load_dotenv()

True

In [9]:
url = os.getenv("QDRANT_URL")
qdrant_api = os.getenv("QDRANT_API")

In [12]:
embedding = OpenAIEmbeddings(
    model='text-embedding-3-small',
)

In [30]:
documents=[]
for i in range(len(data[0])):
    review_id = data[0]['review_id'][i]
    order_id = data[0]['order_id'][i]
    review_score = data[0]['review_score'][i]
    review_title = data[0]['review_comment_title'][i]
    review = data[0]['review_comment_message'][i]
    if pd.isna(review):
        pass
    else:
        doc = Document(
            page_content=review,
            metadata={
                "review_id": review_id,
                "order_id": order_id,
                "review_score": int(review_score),
                "review_title": review_title
            },
        )
        documents.append(doc)

In [32]:
from uuid import uuid4
uuids = [str(uuid4()) for _ in range(len(documents))]

In [33]:
qdrant = QdrantVectorStore.from_documents(
    documents,
    embedding,
    url=url,
    api_key=qdrant_api,
    collection_name="olist_data",
)

print("Qdrant sukses simpan data")

KeyboardInterrupt:

In [60]:
data_or = pd.read_csv("/home/hasyim/final_project/Repo-Final-Project-Kelompok-3/data/process/olist_orders_dataset_clean.csv")

In [61]:
kol_waktu_order = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
data_or[kol_waktu_order] = data_or[kol_waktu_order].apply(pd.to_datetime, format='mixed')

In [62]:
data_or.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [63]:
data_or['time_different'] = (data_or["order_delivered_customer_date"] - data_or["order_estimated_delivery_date"]).dt.days

In [64]:
def delivered_satatus(time):
    if time <= 0:
        return "on time"
    elif time > 0:
        return "late"
    else:
        return "not arrived"

data_or["status_delivered"] = data_or["time_different"].apply(delivered_satatus)

In [71]:
data_or["order_status"].unique()

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [72]:
def delivery_group_status(status):
    if status == "delivered":
        return "success"
    elif status == ['invoiced', 'shipped', 'processing', 'created', 'approved']:
        return "in progress"
    else:
        return "failed"

data_or["order_category_status"] = data_or["order_status"].apply(delivery_group_status)

In [74]:
data_or.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
time_different                   2965
status_delivered                    0
order_category_status               0
dtype: int64

In [ ]:
miss[8]